export const FETCHING_AVAILABILITY = "FETCHING_AVAILABILITY";
export const FETCH_AVAILABILITY_SUCCESS = "FETCH_AVAILABILITY_SUCCESS";
export const FETCH_AVAILABILITY_FAILURE = "FETCH_AVAILABILITY_FAILURE";

export const ADD_GROUP = "ADD_GROUP";
export const ADD_GROUP_ERROR = "ADD_GROUP_ERROR";
export const START_ADDING_GROUP = "START_ADDING_GROUP";
export const CANCEL_ADDING_GROUP = "CANCEL_ADDING_GROUP";
export const DELETE_GROUP = "DELETE_GROUP";
export const DELETE_GROUP_ERROR = "DELETE_GROUP_ERROR";
export const DELETE_MEMBER_FROM_GROUP = "DELETE_MEMBER_FROM_GROUP";
export const DELETE_MEMBER_FROM_GROUP_ERROR = "DELETE_MEMBER_FROM_GROUP_ERROR";
export const ADD_MEMBER_TO_GROUP = "ADD_MEMBER_TO_GROUP";
export const ADD_MEMBER_TO_GROUP_ERROR = "ADD_MEMBER_TO_GROUP_ERROR";

export const OPEN_SIDEBAR = "OPEN_SIDEBAR";
export const CLOSE_SIDEBAR = "CLOSE_SIDEBAR";
export const SELECT_SIDEBAR_ITEM = "SELECT_SIDEBAR_ITEM";

export const ADD_PERSON = "ADD_PERSON";
export const ADD_PERSON_ERROR = "ADD_PERSON_ERROR";
export const CHANGE_PERSON_NAME = "CHANGE_PERSON_NAME";
export const CHANGE_PERSON_NAME_ERROR = "CHANGE_PERSON_NAME_ERROR";

export const ADD_AVAIL = "ADD_AVAIL";
