export const FETCHING_AVAILABILITY = "FETCHING_AVAILABILITY";
export const FETCH_AVAILABILITY_SUCCESS = "FETCH_AVAILABILITY_SUCCESS";
export const FETCH_AVAILABILITY_FAILURE = "FETCH_AVAILABILITY_FAILURE";

export const ADD_GROUP = "ADD_GROUP";
